"""Stable reason-code catalogue (api-contracts.md section 1.4).

A single flat enum, grouped by family only in comments, because the API
contract treats `reason_code` as one interchangeable catalogue across every
`reason_code` field in the system (validation envelopes, rule failures,
audit events). Downstream layers must import `ReasonCode` members rather than
scatter bare string literals through the codebase.
"""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    """Stable, typed reason codes shared by every deterministic service."""

    # Money and dates
    ZERO_AMOUNT = "ZERO_AMOUNT"
    NEGATIVE_AMOUNT = "NEGATIVE_AMOUNT"
    OVER_PRECISION = "OVER_PRECISION"
    FLOAT_NOT_ALLOWED = "FLOAT_NOT_ALLOWED"
    OVER_BALANCE = "OVER_BALANCE"
    BELOW_MIN_AMOUNT = "BELOW_MIN_AMOUNT"
    PAST_DATE = "PAST_DATE"
    OUTSIDE_WINDOW = "OUTSIDE_WINDOW"

    # Records and state
    CONFLICTING_ACTIVE_ITEM = "CONFLICTING_ACTIVE_ITEM"
    DISPUTED_ITEM = "DISPUTED_ITEM"
    STALE_DATA = "STALE_DATA"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    PROPOSAL_INVALID = "PROPOSAL_INVALID"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    CASE_ALREADY_DECIDED = "CASE_ALREADY_DECIDED"
    WRONG_QUEUE = "WRONG_QUEUE"
    INCONSISTENT_RECORD = "INCONSISTENT_RECORD"

    # Policy and authority
    NOT_PERMITTED_BY_POLICY = "NOT_PERMITTED_BY_POLICY"
    EXCEPTION_TYPE_NOT_PERMITTED = "EXCEPTION_TYPE_NOT_PERMITTED"
    EXCEEDS_THRESHOLD = "EXCEEDS_THRESHOLD"
    EXCEEDS_MAX_OVERDUE_AMOUNT = "EXCEEDS_MAX_OVERDUE_AMOUNT"
    WRONG_REVIEWER_ROLE = "WRONG_REVIEWER_ROLE"
    QUEUE_NOT_PERMITTED = "QUEUE_NOT_PERMITTED"
    POLICY_UNAVAILABLE = "POLICY_UNAVAILABLE"
    AMBIGUOUS_VALIDATION = "AMBIGUOUS_VALIDATION"

    # Contact policy
    MAX_ATTEMPTS = "MAX_ATTEMPTS"
    MIN_INTERVAL = "MIN_INTERVAL"

    # Validation
    FIELD_INVALID = "FIELD_INVALID"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    REASON_REQUIRED = "REASON_REQUIRED"
    NOTE_REQUIRED = "NOTE_REQUIRED"
    OUTCOME_REQUIRED = "OUTCOME_REQUIRED"
    MODIFICATION_REQUIRED = "MODIFICATION_REQUIRED"
    ESCALATE_REASON_REQUIRED = "ESCALATE_REASON_REQUIRED"
    ESCALATE_REASON_NOT_WHITELISTED = "ESCALATE_REASON_NOT_WHITELISTED"
    DESTINATION_NOT_ACCEPTED = "DESTINATION_NOT_ACCEPTED"
    FREE_FORM_AMOUNT_NOT_ALLOWED = "FREE_FORM_AMOUNT_NOT_ALLOWED"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    FILTER_REQUIRED = "FILTER_REQUIRED"
    CUSTOMER_ID_REQUIRED_OR_FORBIDDEN = "CUSTOMER_ID_REQUIRED_OR_FORBIDDEN"
