"""One turn's classify-and-respond orchestration (E6-S1; extended by E6-S2/
E6-S3 for proposal creation and by E7-S1 for real escalation-case creation),
split out of `chat_flow.py` to keep that module under the code-gen skill's
300-line block threshold. `chat_flow.process_customer_message` is the only
caller. Classification itself and its unclassifiable-fallback response live
in the sibling `_chat_classification.py` module.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy.ext.asyncio import AsyncSession

from collectai.ai_orchestration.safety_precedence import apply_safety_precedence
from collectai.application._chat_classification import classify, respond_unclassifiable
from collectai.application._chat_dispute_flow import build_dispute_reply
from collectai.application._chat_escalation_reporting import report_escalation
from collectai.application._chat_persistence import persist_message, persist_turn
from collectai.application._chat_proposal_flow import build_proposal_reply
from collectai.application._chat_reply_planning import plan_reply
from collectai.application._chat_templates import HANDED_OFF_HOLDING_MESSAGE, SAFE_FALLBACK_MESSAGE
from collectai.application._chat_types import TurnOutcome
from collectai.audit.service import AuditService
from collectai.config.policy.provider import PolicyProvider
from collectai.domain_services.escalation_service import create_escalation
from collectai.llm_provider.base import LlmProvider
from collectai.persistence.orm.chat_message import ChatMessageOrm
from collectai.persistence.orm.conversation import ConversationOrm
from collectai.types.clock import Clock
from collectai.types.enums import (
    CaseSource,
    ContentSource,
    EscalationReason,
    Intent,
    MessageLabel,
    MessageRole,
    ProviderMode,
)
from collectai.types.enums import SafeState as _SafeState

_TRANSACTIONAL_PROPOSAL_INTENTS = frozenset(
    {Intent.PAY_NOW, Intent.PROMISE_TO_PAY, Intent.PAYMENT_PLAN}
)


async def respond_handed_off(
    session: AsyncSession,
    *,
    conversation: ConversationOrm,
    customer_id: str,
    customer_message: ChatMessageOrm,
    correlation_id: str,
    now: datetime,
    turn_id: str,
) -> TurnOutcome:
    """api-contracts.md 3.8: "In a HANDED_OFF conversation replies are
    templated holding messages without a provider call for that topic." No
    classification, no clarification-count change, no new escalation report
    (one was already reported the turn this conversation became
    HANDED_OFF). `turn_id` was already generated by the caller and set on
    `customer_message` -- see `_chat_persistence`'s module docstring."""
    assistant_message = await persist_message(
        session,
        conversation_id=conversation.conversation_id,
        customer_id=customer_id,
        role=MessageRole.ASSISTANT,
        content=HANDED_OFF_HOLDING_MESSAGE,
        content_source=ContentSource.TEMPLATE,
        labels=[MessageLabel.HUMAN_HANDOFF],
        created_at=now,
        turn_id=turn_id,
    )
    turn = await persist_turn(
        session,
        turn_id=turn_id,
        conversation_id=conversation.conversation_id,
        customer_id=customer_id,
        customer_message=customer_message,
        assistant_message=assistant_message,
        intent=None,
        safe_state=_SafeState.NONE.value,
        correlation_id=correlation_id,
        created_at=now,
    )
    return TurnOutcome(
        turn=turn,
        customer_message=customer_message,
        assistant_message=assistant_message,
        intent=None,
        safe_state=_SafeState.NONE,
        escalation_reported=False,
        escalation_reason=None,
    )


async def classify_and_respond(
    session: AsyncSession,
    *,
    conversation: ConversationOrm,
    customer_id: str,
    customer_message: ChatMessageOrm,
    content: str,
    now: datetime,
    correlation_id: str,
    provider: LlmProvider,
    provider_mode: ProviderMode,
    audit_service: AuditService,
    ai_retry_bound: int,
    max_clarification_turns: int,
    policy_provider: PolicyProvider,
    clock: Clock,
    proposal_ttl_minutes: int,
    turn_id: str,
) -> TurnOutcome:
    result = await classify(
        conversation=conversation,
        content=content,
        correlation_id=correlation_id,
        provider=provider,
        provider_mode=provider_mode,
        audit_service=audit_service,
        ai_retry_bound=ai_retry_bound,
        customer_id=customer_id,
    )

    if result.structured_output is None or not result.governed:
        return await respond_unclassifiable(
            session,
            conversation=conversation,
            customer_id=customer_id,
            customer_message=customer_message,
            correlation_id=correlation_id,
            safe_state=result.safe_state,
            now=now,
            turn_id=turn_id,
        )

    intent_result = result.structured_output
    decision = apply_safety_precedence(intent_result)
    plan = plan_reply(
        intent_result, decision, conversation.clarification_count, max_clarification_turns
    )

    conversation.clarification_count = plan.clarification_count
    conversation.status = plan.conversation_status.value

    escalation_case = None
    if plan.escalation_reason is not None:
        await report_escalation(
            session=session,
            audit_service=audit_service,
            correlation_id=correlation_id,
            customer_id=customer_id,
            account_id=conversation.account_id,
            reason=plan.escalation_reason,
        )
        creation = await create_escalation(
            session,
            reason=plan.escalation_reason,
            customer_id=customer_id,
            account_id=conversation.account_id,
            conversation_id=conversation.conversation_id,
            item_id=None,
            source=_case_source_for(plan.escalation_reason),
            policy_provider=policy_provider,
            clock=clock,
            audit_service=audit_service,
            correlation_id=correlation_id,
        )
        escalation_case = creation.case

    escalation_reason = plan.escalation_reason
    reply_content = plan.content
    reply_labels: list[MessageLabel] = list(plan.labels)
    safe_state = _SafeState.NONE
    proposal_row = None
    if plan.escalation_reason is None and intent_result.label is Intent.DISPUTE:
        # E8-S3 AC1/AC4: `_plan_sensitive` already chose the customer-facing
        # message (AC2's fixed template, never overridden here) and left
        # `escalation_reason` `None` by design (`_chat_escalation_reporting`
        # 's own docstring: DISPUTE's real case creation belongs to this
        # story, not that one) -- this branch does the actual `Dispute`/
        # `EscalationCase` writes `report_escalation`'s audit-only signal
        # above intentionally does not.
        dispute_outcome = await build_dispute_reply(
            session,
            conversation=conversation,
            customer_id=customer_id,
            content=content,
            correlation_id=correlation_id,
            provider=provider,
            provider_mode=provider_mode,
            audit_service=audit_service,
            ai_retry_bound=ai_retry_bound,
            policy_provider=policy_provider,
            clock=clock,
        )
        escalation_case = dispute_outcome.result.escalation.case
        escalation_reason = EscalationReason.DISPUTE
    elif (
        plan.escalation_reason is None
        and decision.proposal_execution_permitted
        and intent_result.label in _TRANSACTIONAL_PROPOSAL_INTENTS
    ):
        proposal_outcome = await build_proposal_reply(
            session,
            conversation=conversation,
            customer_id=customer_id,
            content=content,
            intent_label=intent_result.label,
            correlation_id=correlation_id,
            provider=provider,
            provider_mode=provider_mode,
            audit_service=audit_service,
            ai_retry_bound=ai_retry_bound,
            policy_provider=policy_provider,
            clock=clock,
            proposal_ttl_minutes=proposal_ttl_minutes,
        )
        if proposal_outcome.ai_unavailable:
            reply_content = SAFE_FALLBACK_MESSAGE
            reply_labels = []
            safe_state = _SafeState.AI_UNAVAILABLE
        elif proposal_outcome.policy_unavailable:
            reply_content, reply_labels, safe_state = (
                SAFE_FALLBACK_MESSAGE,
                [],
                _SafeState.POLICY_UNAVAILABLE,
            )
        else:
            reply_content = proposal_outcome.content
            reply_labels = list(proposal_outcome.labels)
            proposal_row = proposal_outcome.proposal

    assistant_message = await persist_message(
        session,
        conversation_id=conversation.conversation_id,
        customer_id=customer_id,
        role=MessageRole.ASSISTANT,
        content=reply_content,
        content_source=ContentSource.TEMPLATE,
        labels=reply_labels,
        created_at=now,
        turn_id=turn_id,
    )
    turn = await persist_turn(
        session,
        turn_id=turn_id,
        conversation_id=conversation.conversation_id,
        customer_id=customer_id,
        customer_message=customer_message,
        assistant_message=assistant_message,
        intent=intent_result.model_dump(mode="json"),
        safe_state=safe_state.value,
        correlation_id=correlation_id,
        created_at=now,
        proposal_id=proposal_row.proposal_id if proposal_row is not None else None,
    )
    return TurnOutcome(
        turn=turn,
        customer_message=customer_message,
        assistant_message=assistant_message,
        intent=intent_result,
        safe_state=safe_state,
        escalation_reported=escalation_reason is not None,
        escalation_reason=escalation_reason,
        proposal=proposal_row,
        escalation_case=escalation_case,
    )


def _case_source_for(reason: EscalationReason) -> CaseSource:
    """AC1's two Group-G-wired triggers: REQUEST_HUMAN is a direct customer
    ask (`CaseSource.CUSTOMER`); UNRESOLVED_UNKNOWN is the deterministic chat
    flow giving up after `max_clarification_turns` (`CaseSource.SYSTEM`),
    never `CaseSource.AI` -- no LLM output decides this trigger."""
    return CaseSource.CUSTOMER if reason is EscalationReason.REQUEST_HUMAN else CaseSource.SYSTEM
