"""Intent classification and its unclassifiable-fallback response (E6-S1),
split out of `_chat_turn_processing.py` to keep that module under the
code-gen skill's 300-line block threshold once E6-S2/E6-S3's proposal
wiring was added. `_chat_turn_processing.classify_and_respond` is the only
caller of both functions here.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy.ext.asyncio import AsyncSession

from collectai.ai_orchestration.orchestrator import (
    AiCallContext,
    AiInteractionResult,
    run_ai_interaction,
)
from collectai.ai_orchestration.prompts.builder import AllowedPromptContext
from collectai.ai_orchestration.prompts.intent_v1 import PROMPT_VERSION, build_intent_request
from collectai.ai_orchestration.schemas.intent import IntentResult
from collectai.application._chat_persistence import persist_message, persist_turn
from collectai.application._chat_templates import SAFE_FALLBACK_MESSAGE
from collectai.application._chat_types import TurnOutcome
from collectai.audit.service import AuditService
from collectai.llm_provider.base import LlmProvider
from collectai.persistence.orm.chat_message import ChatMessageOrm
from collectai.persistence.orm.conversation import ConversationOrm
from collectai.types.enums import ContentSource, MessageLabel, MessageRole, Persona, ProviderMode
from collectai.types.enums import SafeState as _SafeState

_CHAT_CAPABILITY = "INTENT_CLASSIFICATION"


async def classify(
    *,
    conversation: ConversationOrm,
    content: str,
    correlation_id: str,
    provider: LlmProvider,
    provider_mode: ProviderMode,
    audit_service: AuditService,
    ai_retry_bound: int,
    customer_id: str,
) -> AiInteractionResult[IntentResult]:
    context = AllowedPromptContext(
        customer_display_name=customer_id, account_reference=conversation.account_id
    )
    request = build_intent_request(context=context, message=content)
    call_context = AiCallContext(
        correlation_id=correlation_id,
        capability=_CHAT_CAPABILITY,
        prompt_version=PROMPT_VERSION,
        provider_name="anthropic" if provider_mode is ProviderMode.LIVE else "mock",
        provider_mode=provider_mode,
        actor_persona=Persona.CUSTOMER,
        customer_id=customer_id,
        account_id=conversation.account_id,
    )
    return await run_ai_interaction(
        provider,
        request,
        IntentResult,
        call_context,
        audit_service,
        domain_port=None,
        retry_bound=ai_retry_bound,
    )


async def respond_unclassifiable(
    session: AsyncSession,
    *,
    conversation: ConversationOrm,
    customer_id: str,
    customer_message: ChatMessageOrm,
    correlation_id: str,
    safe_state: _SafeState,
    now: datetime,
    turn_id: str,
) -> TurnOutcome:
    """AC1/api-contracts.md 3.8: a provider failure or an audit write
    failure for the classification itself both fail closed to the same safe
    fallback -- `talk_to_human_available` stays true either way (that flag
    is constant across every response this router returns, not conditional
    on this branch). `turn_id` was already generated by the caller and set
    on `customer_message` -- see `_chat_persistence`'s module docstring."""
    assistant_message = await persist_message(
        session,
        conversation_id=conversation.conversation_id,
        customer_id=customer_id,
        role=MessageRole.ASSISTANT,
        content=SAFE_FALLBACK_MESSAGE,
        content_source=ContentSource.TEMPLATE,
        labels=[MessageLabel.SAFE_FALLBACK],
        created_at=now,
        turn_id=turn_id,
    )
    turn = await persist_turn(
        session,
        turn_id=turn_id,
        conversation_id=conversation.conversation_id,
        customer_id=customer_id,
        customer_message=customer_message,
        assistant_message=assistant_message,
        intent=None,
        safe_state=safe_state.value,
        correlation_id=correlation_id,
        created_at=now,
    )
    return TurnOutcome(
        turn=turn,
        customer_message=customer_message,
        assistant_message=assistant_message,
        intent=None,
        safe_state=safe_state,
        escalation_reported=False,
        escalation_reason=None,
    )
