"""Escalation, review-queue and case-decision enums (api-contracts.md section 5)."""

from __future__ import annotations

from enum import StrEnum


class EscalationReason(StrEnum):
    REQUEST_HUMAN = "REQUEST_HUMAN"
    UNRESOLVED_UNKNOWN = "UNRESOLVED_UNKNOWN"
    AI_FAILURE_FALLBACK = "AI_FAILURE_FALLBACK"
    EXCEPTIONAL_ARRANGEMENT = "EXCEPTIONAL_ARRANGEMENT"
    FINANCIAL_HARDSHIP = "FINANCIAL_HARDSHIP"
    DISPUTE = "DISPUTE"
    SETTLEMENT_REQUEST = "SETTLEMENT_REQUEST"
    AMBIGUOUS_VALIDATION = "AMBIGUOUS_VALIDATION"
    VULNERABLE_CUSTOMER = "VULNERABLE_CUSTOMER"
    POLICY_EXCEPTION = "POLICY_EXCEPTION"
    HIGH_RISK_COMPLIANCE = "HIGH_RISK_COMPLIANCE"


class ReviewQueue(StrEnum):
    COLLECTIONS_REVIEW = "COLLECTIONS_REVIEW"
    COLLECTIONS_EXCEPTION_REVIEW = "COLLECTIONS_EXCEPTION_REVIEW"
    HARDSHIP_REVIEW = "HARDSHIP_REVIEW"
    DISPUTE_REVIEW = "DISPUTE_REVIEW"
    VULNERABLE_CUSTOMER_REVIEW = "VULNERABLE_CUSTOMER_REVIEW"
    COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"


class EscalationPriority(StrEnum):
    NORMAL = "NORMAL"
    ELEVATED = "ELEVATED"
    URGENT = "URGENT"


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    AWAITING_INFORMATION = "AWAITING_INFORMATION"
    DECIDED = "DECIDED"
    RE_ROUTED = "RE_ROUTED"


class ReviewAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    MODIFY = "MODIFY"
    REQUEST_MORE_INFORMATION = "REQUEST_MORE_INFORMATION"
    ESCALATE = "ESCALATE"


class DecisionKind(StrEnum):
    REVIEWER_ACTION = "REVIEWER_ACTION"
    COMPLIANCE_DECISION = "COMPLIANCE_DECISION"
    START_REVIEW = "START_REVIEW"


class ComplianceOutcome(StrEnum):
    CLEARED = "CLEARED"
    NOT_CLEARED = "NOT_CLEARED"
    REMEDIATION_REQUIRED = "REMEDIATION_REQUIRED"


class ExceptionType(StrEnum):
    TERM = "TERM"
    START_DATE = "START_DATE"
    AMOUNT_STRUCTURE = "AMOUNT_STRUCTURE"


class EligibilityClass(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    EXCEPTIONAL = "EXCEPTIONAL"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
