"""Vulnerability, hardship and dispute enums (api-contracts.md section 5)."""

from __future__ import annotations

from enum import StrEnum


class VulnerabilityCategory(StrEnum):
    BEREAVEMENT = "BEREAVEMENT"
    SERIOUS_ILLNESS_OR_DISABILITY = "SERIOUS_ILLNESS_OR_DISABILITY"
    MENTAL_HEALTH_CONCERN = "MENTAL_HEALTH_CONCERN"
    DOMESTIC_ABUSE_OR_COERCION = "DOMESTIC_ABUSE_OR_COERCION"
    LIMITED_CAPACITY_TO_UNDERSTAND = "LIMITED_CAPACITY_TO_UNDERSTAND"
    LANGUAGE_OR_COMMUNICATION_BARRIER = "LANGUAGE_OR_COMMUNICATION_BARRIER"
    OTHER = "OTHER"


class HardshipIndicatorType(StrEnum):
    JOB_LOSS = "JOB_LOSS"
    INCOME_REDUCTION = "INCOME_REDUCTION"
    MEDICAL_OR_FAMILY_EMERGENCY = "MEDICAL_OR_FAMILY_EMERGENCY"
    TEMPORARY_FINANCIAL_DIFFICULTY = "TEMPORARY_FINANCIAL_DIFFICULTY"
    OTHER = "OTHER"


class HardshipStatus(StrEnum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    DECIDED = "DECIDED"


class DisputeCategory(StrEnum):
    AMOUNT_INCORRECT = "AMOUNT_INCORRECT"
    NOT_MY_DEBT = "NOT_MY_DEBT"
    ALREADY_PAID = "ALREADY_PAID"
    FRAUD_OR_UNAUTHORIZED = "FRAUD_OR_UNAUTHORIZED"
    FEE_OR_INTEREST_DISPUTE = "FEE_OR_INTEREST_DISPUTE"
    OTHER = "OTHER"


class DisputeStatus(StrEnum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"


class DisputeOutcome(StrEnum):
    UPHELD = "UPHELD"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
